# SPDX-FileCopyrightText: 2024-2025 wucke13
#
# SPDX-License-Identifier: Apache-2.0

policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      dco: true
      spellcheck:
        locale: US
      conventional:
        types:
          - "chore"
          - "refactor"
        scopes:
          - "scope"
        descriptionLength: 72
