# SPDX-FileCopyrightText: 2025-2026 wucke13
#
# SPDX-License-Identifier: Apache-2.0

on: [push]

jobs:
  flake-show:
    name: nix flake show
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          # checkout full tree
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: wucke13
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Show flake outputs
        run: nix flake show --quiet

  check-commits:
    name: Check commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CHECK_COMMAND:
          - conform enforce
          - nix fmt -- --ci
          - reuse lint
    steps:
      - uses: actions/checkout@v6
        with:
          # checkout full tree
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: wucke13
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Checking each commit
        run: nix shell --inputs-from . .#check-commits nixpkgs#conform nixpkgs#reuse --command ${{ matrix.CHECK_COMMAND }}

  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # The default image contains dozens of gigabytes of tools. NixOS config builds get big. Thus,
      # remove unused tools (Nix provides for all we need!) to get some space.
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: wucke13
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check

  build:
    name: nix build
    needs: [check-commits, flake-check]
    strategy:
      matrix:
        RUNNER:
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
    runs-on: ${{ matrix.RUNNER }}
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: wucke13
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run --inputs-from . nixpkgs#nix-fast-build -- -f .#ciJobs --systems "$(nix eval --raw --impure --expr builtins.currentSystem)" --no-nom --skip-cached --result-file result-junit.xml --result-format junit
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "result-junit.xml"
        if: always()
