on: [push]

env:
  EXTRA_NIX_FLAGS: --log-format raw-with-logs --print-build-logs

jobs:
  check:
    name: Nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: wucke13
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check
  build-pkg:
    name: ${{ matrix.pkg }} for ${{ matrix.system }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system:
          # TODO make this work well
          # - "aarch64-linux"
          - x86_64-linux
        pkg:
          - check-commits
          - update-ci
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: wucke13
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: supported-system
        name: Skip unsupported builds
        run: nix eval --json .#packages.${{ matrix.system }}.${{ matrix.pkg }}.meta.available
      - if: steps.supported-system.conclusion == 'success'
        run: nix build $EXTRA_NIX_FLAGS .#packages.${{ matrix.system }}.${{ matrix.pkg }}

  build-nixos-config:
    name: NixOS on ${{ matrix.config }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Generated using
        # nix eval --json --apply builtins.attrNames .\#nixosConfigurations
        config:
          - minimal
          - minimal-cross-x86_64-aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: wucke13
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build $EXTRA_NIX_FLAGS .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel
